### ISSUE TITLE
PowerLab Web Sitesi Güncellenmesi

### ISSUE THREAD

**Issue by ozank** [odtu/powerlab#1]
- [ ]  Kişiler kısmının güncellenmesi (gidenler, yeni başlayanlar)
- [x]  Projeler kısmının güncellenmesi (mevcut projelerle ilgili kısa bilgi + görsel)
- [ ]  Açık pozisyonlar kısmının güncellenmesi
- [ ] En son yayınlar, gidilen konferanslarla ilgili resim eklenmesi ( @dogaceylan @mesutto )

**Comment by ozank** [comment]
Ne oldu konferans resimleri?
Semınerlerde cektigimiz resimler?

**Comment by ErencanDuymaz** [comment]
konferans resimlerini istedim hocam. Resimler gelince seminer resimleriyle beraber güncellicem
