### ISSUE TITLE
PCB-Sarf Sipariş Kasım - 2024

### ISSUE THREAD

**Issue by OgunAltun** [odtu/Powerlab#21]
Yakın zamanda üretime gidecek PCB ve sarf malzemelerimiz için tarih belirleyelim. Birlikte olabilecek siparişleri ortaklayalım.

**Comment by OgunAltun** [comment]
**Voltage Measurement PCB:** Tasarım tamamlandı. Fiyat teklifi hazır. Satın alma başlatılacak.
**Voltage Measurement PCB-BOM:** BOM hazır. Teklif alınmadı.

**Comment by ozank** [comment]
Bu Cuma'ya kadar tasarımı bitenleri gönderiyoruz. 
Bi daha ne zaman gider kısmet
