### ISSUE TITLE
Utility Software Repository

### ISSUE THREAD

**Issue by ozgurgulsuna** [odtu/Powerlab#22]

**Comment by ozgurgulsuna** [comment]
hakansrc/fault_tolerant_drives/tree/master/Software/MultipleDataPlot/HandBook

**Comment by ozank** [comment]
1 ayda yol katedemedik mi 😒

**Comment by ozgurgulsuna** [comment]
Issue #37 ile aynı, bu devam etsin diğerini kapatalım

**Comment by ozank** [comment]
Utility repo açıldı ama içi hala boş sanırım...
