### ISSUE TITLE
MAM Projesi için Repo Açılması

### ISSUE THREAD

**Issue by ozank** [odtu/Powerlab#33]

**Comment by ozank** [comment]
@Gktut MAM 1004 projesi için elimizdeki tüm dosyaları düzenleyip bir repoya koyabilir misin? Proje biterken elimizde derli toplu arşiv dursun

**Comment by Gktut** [comment]
Hocam tasarım dosyaları vs yedek diskimde, aktif proje olmadığı için bilgisayarda sadece kodu tutuyorum. Hafta içi çekip yüklerim, iskender ile iletişime geçtik geçen hafta öncelikli olarak orasıyla konuştuğumuz kısımlarla uğraşıyorum
