### ISSUE TITLE
3D Jeneratör Baskısı (Samet'in Tez Sunumu için)

### ISSUE THREAD

**Issue by ozgurgulsuna** [odtu/Powerlab#36]

**Comment by KaanDemirkoparan** [comment]
- Parçaların çoğu ayrı ayrı basıldı. Önceki basılan karkas EÜAŞ ekibine hediye edilmiş, o sebeple şuanda (Pazar gece 00.48) yeni karkas tekrardan baskıya verildi. Pazartesi sabaha çıkmış olur. Tüm parçalar bittikten sonra birbirlerine sıkı geçme şekilde oturtularak birleştirilecekler.

![Image](https://github.com/user-attachments/assets/4b69d1e3-b0e5-4acd-a5a8-d1a376dc0a17)
![Image](https://github.com/user-attachments/assets/6d0c6764-36c2-4305-b1bb-4a3f92f77f85)

- Montaj Videosu: 

https://github.com/user-attachments/assets/b69a9ac7-7275-4d83-9510-0aacff68a3c0
