### ISSUE TITLE
Lab İçi Gömülü Yazılım Kütüphaneleri Oluşturulması

### ISSUE THREAD

**Issue by ozank** [odtu/Powerlab#37]

**Comment by ozgurgulsuna** [comment]
Bir tane repo olsun ve onun üzerinden herkes aynı kütüphaneyi indirip devam etsin ve geliştirsin.
Hemen bitmesi gerekmiyor, iş yapıldıkça burada saklansın.

**Comment by ozgurgulsuna** [comment]
Repo açılsın,
  - TI
     - FOC
  - ST
     - Encoder etc
