### ISSUE TITLE
EE463 Hazırlıkları

### ISSUE THREAD

**Issue by ozank** [odtu/powerlab#4]
- [ ]  Ödev taslaklarının oluşturulması
- [ ]  Proje taslağının oluşturulması
- [ ] Syllabus oluşturulması
- [ ]  PSim vs Simunlink?

**Comment by ilkersahin78** [comment]
Bence;

# Syllabus

Introduction
Devices 1 (diode, thyristor)  ---> 1 week

Fund. Principles (V.sec, A.sec balance, cont. of current etc.)
1 Phase Rectifiers (controlled & uncontrolled) ---> 2.5 week

3 Phase Rectifiers (controlled and uncontrolled)  ---> 2.5 week

Devices 2 (mosfet, igbt) & Losses - Efficiency - Thermal  ---> 1 week

Intro. to DC-DC (Buck Boost Buck-Boost)  ---> 2.5 week

Intro to DC-AC (space vectors, PWM)  ---> 1.5 week

Total:11. Rest: Review, QA, Problem solving etc.

Textbook: Mohan 
Supplementary: Erickson

# Psim - Simulink

Oyum Simulink ten yana ama Psim i de sıkıntısız götürürüm. Psim in arayüzü baydı Win98 gibi.

# Proje

1- Dimmer
2- (Labdaki 3 Phase Thyristor Set i kullanarak) AC-DC ile DC motor sürsünler, hızı Va ile kontrol etsinler, sonraki aşamada da mesela 5 ve 7 ye tune edilmiş filtre taksınlar rectifier girişine.
3- (Syllabus da olursa) Buck converter. 

# Ödev

Ödevleri çoralım eskiden veya kitaptaki örneklerin simülasyonunu verebiliriz, kitabı bi incelemeli.

**Comment by ozank** [comment]
syllabus iyi de 1.5 haftada DC/AC anlatılır mı, bi de 464 de ne anlatacaz la tum konuları bitirince :smile: 

Odevlerden fikir anlamında bir planlama yaparsan guzel olur syllabusta dedigin QA sessionlarını odevlerle senkronize ederiz.

**Comment by ilkersahin78** [comment]
Zaten mohanda da inverter yok, biraz modulation indexten bahseder o kadar. 2 hafta olsa bile mohandaki kısmına rahat yeter.

Şunu buldum, Fred Lee reisin mekanı Virginia Tech undergrad power elec. syllabus:

https://www.ece.vt.edu/undergrad/courses/4224

Adamlarda diode rectifier hiç yok. Bizde ise dön baba dönelim rectifier. Çoğaltabilirim örnekleri.

464 e konu kalıyor aslında: magnetic design, smps (buck boost + isolated topologies), inverter, control (small signal modelling, current mode control, dq transform), intro to renewables, simülasyon + hardware projesi oh mis.

**Comment by ozank** [comment]
Derste online birkaç deneme yaptırmak için şu nasıl sence?
https://www.multisim.com

**Comment by ilkersahin78** [comment]
İnceliyorum

**Comment by ilkersahin78** [comment]
![buck olmuyo-schematic](https://user-images.githubusercontent.com/12057501/30184799-e05cd49e-9427-11e7-8c2e-29ec039ef193.png)

**Comment by ilkersahin78** [comment]
Yarım saatte bi buck yapamadım. Fikir güzel de program leş.

**Comment by ozank** [comment]
bi de şu llinklere baktıktan sonra yorumunu alayım
Ornek devreler
https://www.multisim.com/discover/

Power elektronik kısmı
https://www.multisim.com/content/XW8cDBaxnCm2Y3KbDChwnU/simple-buck-converter/
http://www.ni.com/white-paper/14742/en/#toc1
http://www.ni.com/white-paper/14677/en/

**Comment by ilkersahin78** [comment]
İnceledim de büyük haksızlık etmişim multisime. Hazır devreler baya güzel. Derste çok işe yarar.

Aklıma şöyle bir örnek geldi. Buck ı anlattınız simülasyon koştu waveformlar göründü. Output resistansı artırsam nolur .... avg inductor current düştü ..... discontiuous cond mode ...... converter karakteri değişti ... Tahtada mikmik etmektense izleyerek anlarlar
